apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Chart.Name }}-ingress"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: demo-app-cont.corp.deepfactor.io 
    http:
      paths:
      - path: /
      #- path: /webserver
        backend:
          serviceName: "{{  .Chart.Name }}-service"
          servicePort: {{ .Values.service.externalPort }}                  
